### ISSUE TITLE
Cannot build with XCode 12.5

### ISSUE THREAD

**Issue by lucaspal** [ezet/stripe-sdk#137]
The package is not compatible with the latest Apple CLang compiler, used by XCode 12.5, resulting in builds failing with the following error:

```
    /<my_project>/ios/Pods/Stripe/Stripe/STPPinManagementService.m:51:81: error: 'new' is unavailable: You cannot directly instantiate an STPIssuingCardPin
                                                    deserializer:[STPIssuingCardPin new]
                                                                                    ^

In file included from /<my_project>/ios/Pods/Stripe/Stripe/STPPinManagementService.m:11:
    /<my_project>/ios/Pods/Stripe/Stripe/PublicHeaders/STPIssuingCardPin.h:22:1: note: 'init' has been explicitly marked unavailable here
    - (instancetype)init __attribute__((unavailable("You cannot directly instantiate an STPIssuingCardPin")));
    ^

    /<my_project>/ios/Pods/Stripe/Stripe/STPPinManagementService.m:101:81: error: 'new' is unavailable: You cannot directly instantiate an STPIssuingCardPin
                                                    deserializer:[STPIssuingCardPin new]
                                                                                    ^
In file included from /<my_project>/ios/Pods/Stripe/Stripe/STPPinManagementService.m:11:
    /<my_project>/ios/Pods/Stripe/Stripe/PublicHeaders/STPIssuingCardPin.h:22:1: note: 'init' has been explicitly marked unavailable here
    - (instancetype)init __attribute__((unavailable("You cannot directly instantiate an STPIssuingCardPin")));
```

From a first look at the changelog from Apple (available [here](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-release-notes)), the reason of the failure seems to be the following:

> Clang now infers the availability of +new from availability annotations on -init methods. Since +new calls [[Foo alloc] init], +new isn’t available unless +init is available. (75884815)

__________________________________
Details:
- Flutter version: 2.0.5
- XCode version: 12.5
- stripe_sdk version: 4.0.2 (Same happens with 3.2.0)

**Comment by Alecsplus** [comment]
Any news on this issue? This unfortunately makes us impossible to adopt this plugin. Thanks for all.

**Comment by ezet** [comment]
No, I am unable to debug the issue as I don't use Apple devices. Any
suggestions or PRs would be appreciated.

**Comment by lucaspal** [comment]
@ezet Could you add some labels to make that more explicit? 

E.g. iOS, help wanted, bug

**Comment by lucaspal** [comment]
@ezet I am closing this issue since the error that I had was not related with this library. 

There is, in fact, no way this package can be broken on newer versions of XCode, being this a native Dart package and, thus, not containing any native Swift code. 

In my case, there was another package that was using an outdated version of the native Stripe SDK (iOS) and that was the one breaking the build. 

Sorry for the inconvenience, I hope this can also help the others.
